project:
  version: @project.version@

spring:
  application:
    name: notification-service-test

  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

  # 🚫 Desactiva SQL/Flyway
  sql:
    init:
      mode: never

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notification_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  flyway:
    enabled: false

  # 📧 Mail simulado (no conecta a nada)
  mail:
    host: localhost
    port: 2525
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  # 🧩 Thymeleaf sin cache para tests
  thymeleaf:
    cache: false

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never
