version: "3.9"
services:
  frontend_dev:
    image: ${NODE_IMAGE}
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks: [ frontend_net ]
