project:
  version: @project.version@

spring:
  application:
    name: order-service
  main.banner-mode: "off"
  sql.init.mode: never
  
  # Configuración web para evitar conflictos con recursos estáticos
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}?currentSchema=${DB_SCHEMA:orders},public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA:orders}
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:orders}
    properties:
      hibernate.default_schema: ${DB_SCHEMA:orders}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:orders}
    default-schema: ${DB_SCHEMA:orders}
    table: ${FLYWAY_TABLE:flyway_history_orders}
    validate-on-migrate: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/r

logging.level:
  root: INFO
  org.hibernate.SQL: WARN
  org.hibernate.type.descriptor.sql.BasicBinder: WARN

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.show-details: never

services:
  payment:
    base-url: ${PAYMENT_SERVICE_URL:http://payment-service:8081}