project:
  version: @project.version@

spring:
  application:
    name: auth-service
  main.banner-mode: "off"
  sql.init.mode: never

  profiles:
    active: prod

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: notifications.exchange
    routing-key: notifications.key

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}?currentSchema=${DB_SCHEMA:auth},public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA:auth}
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:auth}
    properties:
      hibernate.default_schema: ${DB_SCHEMA:auth}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:auth}
    default-schema: ${DB_SCHEMA:auth}
    table: ${FLYWAY_TABLE:flyway_history_auth}
    validate-on-migrate: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/r

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: 900000    # 15 minutos
    refresh: 604800000 # 7 días

logging.level:
  root: INFO
  org.hibernate.SQL: WARN
  org.hibernate.type.descriptor.sql.BasicBinder: WARN

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.show-details: never
