services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16-alpine}
    container_name: ticketera-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-America/Argentina/Cordoba}
    volumes:
      - ${PGDATA_VOL:-ticketera_prod_pgdata}:/var/lib/postgresql/data
      # En prod NO solemos bootstrapear con init.sql. Si lo necesitás para un primer init:
      # - ./infra/postgres/prod/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - backend

  # rabbitmq:
  #   image: ${RABBIT_IMAGE}
  #   container_name: rabbit
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
  #   ports:
  #     - "15672:15672"
  #   networks: [ backend ]

    # Frontend estático servido por Node 'serve'
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    networks: [ frontend_net ]

  # API Gateway WebFlux (Spring Cloud Gateway)
  gateway:
    build:
      context: ./backend/gateway
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:8081"
    depends_on: [ auth, events, tickets, payments, notifications ]
    ports:
      - "${PUBLIC_HTTP_PORT}:8080"
    networks: [ backend, frontend_net ]

  # === Microservicios ===
  
  auth:
    build:
      context: ./backend/auth-service
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: auth
      FLYWAY_TABLE: flyway_history_auth
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_USER: ${RABBIT_USER}
      # RABBITMQ_PASS: ${RABBIT_PASS}
    depends_on: [ postgres ]
    networks: [ backend ]

  events:
    build:
      context: ./backend/event-service
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: events
      FLYWAY_TABLE: flyway_history_events
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_USER: ${RABBIT_USER}
      # RABBITMQ_PASS: ${RABBIT_PASS}
    depends_on: [ postgres ]
    networks: [ backend ]

  tickets:
    build:
      context: ./backend/ticket-service
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: tickets
      FLYWAY_TABLE: flyway_history_tickets
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_USER: ${RABBIT_USER}
      # RABBITMQ_PASS: ${RABBIT_PASS}
    depends_on: [ postgres ]
    networks: [ backend ]

  payments:
    build:
      context: ./backend/payment-service
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: payments
      FLYWAY_TABLE: flyway_history_payments
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_USER: ${RABBIT_USER}
      # RABBITMQ_PASS: ${RABBIT_PASS}
    depends_on: [ postgres ]
    networks: [ backend ]

  notifications:
    build:
      context: ./backend/notification-service
      dockerfile: ./Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        RUNTIME_IMAGE: eclipse-temurin:17-jre
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: notifications
      FLYWAY_TABLE: flyway_history_notifications
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_USER: ${RABBIT_USER}
      # RABBITMQ_PASS: ${RABBIT_PASS}
    depends_on: [ postgres ]
    networks: [ backend ]

networks:
  backend:
  frontend_net:

volumes:
  ticketera_prod_pgdata:
