server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        - id: event
          uri: http://event:8080
          predicates:
            - Path=/api/event/**
          filters:
            - StripPrefix=2

        - id: ticket
          uri: http://ticket:8080
          predicates:
            - Path=/api/ticket/**
          filters:
            - StripPrefix=2

        - id: payments
          uri: http://payments:8080
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2

        - id: notifications
          uri: http://notifications:8080
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2

      # CORS global (ajusta origen/esquemas)
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173, http://localhost:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
