server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 1000

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
