spring:
  config:
    activate:
      on-profile: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: auth
          uri: "${SERVICES_AUTH_BASE_URL:http://auth-dev:8080}"
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /${segment}

        - id: events
          uri: "${SERVICES_EVENT_BASE_URL:http://event-dev:8080}"
          predicates:
            - Path=/api/events/**
          filters:
            - RewritePath=/api/events/?(?<segment>.*), /${segment}

        - id: tickets
          uri: "${SERVICES_TICKET_BASE_URL:http://ticket-dev:8080}"
          predicates:
            - Path=/api/tickets/**
          filters:
            - RewritePath=/api/tickets/?(?<segment>.*), /${segment}

        - id: payments
          uri: "${SERVICES_PAYMENT_BASE_URL:http://payment-dev:8080}"
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/?(?<segment>.*), /${segment}

        - id: notifications
          uri: "${SERVICES_NOTIFICATION_BASE_URL:http://notification-dev:8080}"
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/?(?<segment>.*), /${segment}

        - id: orders
          uri: "${SERVICES_ORDER_BASE_URL:http://order-dev:8080}"
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/?(?<segment>.*), /${segment}

        # --- OpenAPI aggregation ---
        - id: openapi-auth
          uri: http://auth-dev:8080
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs
        - id: openapi-events
          uri: http://event-dev:8080
          predicates:
            - Path=/v3/api-docs/events
          filters:
            - RewritePath=/v3/api-docs/events, /v3/api-docs
        - id: openapi-tickets
          uri: http://ticket-dev:8080
          predicates:
            - Path=/v3/api-docs/tickets
          filters:
            - RewritePath=/v3/api-docs/tickets, /v3/api-docs
        - id: openapi-payments
          uri: http://payment-dev:8080
          predicates:
            - Path=/v3/api-docs/payments
          filters:
            - RewritePath=/v3/api-docs/payments, /v3/api-docs
        - id: openapi-notifications
          uri: http://notification-dev:8080
          predicates:
            - Path=/v3/api-docs/notifications
          filters:
            - RewritePath=/v3/api-docs/notifications, /v3/api-docs
        - id: openapi-orders
          uri: http://order-dev:8080
          predicates:
            - Path=/v3/api-docs/orders
          filters:
            - RewritePath=/v3/api-docs/orders, /v3/api-docs

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:8080"
              - "http://localhost:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth
      - name: events
        url: /v3/api-docs/events
      - name: tickets
        url: /v3/api-docs/tickets
      - name: payments
        url: /v3/api-docs/payments
      - name: notifications
        url: /v3/api-docs/notifications
      - name: orders
        url: /v3/api-docs/orders
    persist-authorization: true
    try-it-out-enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
  server-url: http://localhost:8080
  cors:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      show-details: always
