server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /${segment}

        - id: events
          uri: http://events:8080
          predicates:
            - Path=/api/events/**
          filters:
            - RewritePath=/api/events/?(?<segment>.*), /${segment}

        - id: tickets
          uri: http://tickets:8080
          predicates:
            - Path=/api/tickets/**
          filters:
            - RewritePath=/api/tickets/?(?<segment>.*), /${segment}

        - id: payments
          uri: http://payments:8080
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/?(?<segment>.*), /${segment}

        - id: notifications
          uri: http://notifications:8080
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/?(?<segment>.*), /${segment}

        - id: orders
          uri: http://orders:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/?(?<segment>.*), /${segment}

      # CORS global (ajusta origen/esquemas)
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173, http://localhost:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
