\set ON_ERROR_STOP on
BEGIN;

-- 1) Extensión para UUID (v4) via pgcrypto
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- provee public.gen_random_uuid()

-- 2) Schemas por servicio
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS events;
CREATE SCHEMA IF NOT EXISTS tickets;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS common;

-- 3) Permisos sobre schemas
GRANT USAGE, CREATE ON SCHEMA auth, events, tickets, payments, notifications, common TO CURRENT_USER;

-- 4) Permisos sobre objetos EXISTENTES (si ya hubiera)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES
  IN SCHEMA auth, events, tickets, payments, notifications, common TO CURRENT_USER;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES
  IN SCHEMA auth, events, tickets, payments, notifications, common TO CURRENT_USER;

-- 5) Default privileges para OBJETOS FUTUROS
-- Tablas
ALTER DEFAULT PRIVILEGES IN SCHEMA auth           GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA events         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA tickets        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments       GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA common         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;

-- Secuencias (no las vas a usar con UUID, pero no molestan)
ALTER DEFAULT PRIVILEGES IN SCHEMA auth           GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA events         GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA tickets        GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments       GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA common         GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;

COMMIT;
