\set ON_ERROR_STOP on
BEGIN;

-- 1) Extensión para UUID (v4) via pgcrypto
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- provee public.gen_random_uuid()

-- 2) Schemas por servicio
CREATE SCHEMA IF NOT EXISTS auth_dev;
CREATE SCHEMA IF NOT EXISTS events_dev;
CREATE SCHEMA IF NOT EXISTS tickets_dev;
CREATE SCHEMA IF NOT EXISTS payments_dev;
CREATE SCHEMA IF NOT EXISTS notifications_dev;
CREATE SCHEMA IF NOT EXISTS common;

-- 3) Permisos sobre schemas
GRANT USAGE, CREATE ON SCHEMA auth_dev, events_dev, tickets_dev, payments_dev, notifications_dev, common TO CURRENT_USER;

-- 4) Permisos sobre objetos EXISTENTES (si ya hubiera)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES
  IN SCHEMA auth_dev, events_dev, tickets_dev, payments_dev, notifications_dev, common TO CURRENT_USER;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES
  IN SCHEMA auth_dev, events_dev, tickets_dev, payments_dev, notifications_dev, common TO CURRENT_USER;

-- 5) Default privileges para OBJETOS FUTUROS
-- Tablas
ALTER DEFAULT PRIVILEGES IN SCHEMA auth_dev           GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA events_dev         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA tickets_dev        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments_dev       GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications_dev  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA common         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;

-- Secuencias (no las vas a usar con UUID, pero no molestan)
ALTER DEFAULT PRIVILEGES IN SCHEMA auth_dev           GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA events_dev         GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA tickets_dev        GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments_dev       GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications_dev  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA common         GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;

COMMIT;
