# .github/workflows/commitlint.yml
name: Lint PR Title & Commits
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -D @commitlint/cli @commitlint/config-conventional
      - name: Lint commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.sha }}