# .github/workflows/release-develop.yml
name: Release (pre) - develop
on:
  push:
    branches: [develop]

jobs:
  prerelease-frontend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ticketera/frontend } }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - ticketera/backend/gateway
          - ticketera/backend/auth-service
          - ticketera/backend/event-service
          - ticketera/backend/ticket-service
          - ticketera/backend/payment-service
          - ticketera/backend/notification-service
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: semantic-release ${{ matrix.svc }}
        working-directory: ${{ matrix.svc }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-prerelease:
    runs-on: ubuntu-latest
    needs: [prerelease-frontend, prerelease-backend] # que ya haya corrido semantic-release
    strategy:
      matrix:
        svc:
          - { name: frontend, path: "ticketera/frontend", image: "ticketera-frontend" }
          - { name: gateway,  path: "ticketera/backend/gateway", image: "ticketera-gateway" }
          - { name: auth,     path: "ticketera/backend/auth-service", image: "ticketera-auth-service" }
          - { name: event,    path: "ticketera/backend/event-service", image: "ticketera-event-service" }
          - { name: ticket,   path: "ticketera/backend/ticket-service", image: "ticketera-ticket-service" }
          - { name: payment,  path: "ticketera/backend/payment-service", image: "ticketera-payment-service" }
          - { name: notif,    path: "ticketera/backend/notification-service", image: "ticketera-notification-service" }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          SHA=${GITHUB_SHA::7}
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          # canal 'next' para develop
          echo "tag1=${{ github.ref_name }}-next-${SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.path }}
          file: ${{ matrix.svc.path }}/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.svc.image }}:${{ steps.vars.outputs.tag1 }}
