name: Release (pre) - develop

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  prerelease-frontend:
    name: Pre-release Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Cachea tanto root como frontend
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      # Identidad de git para commits de @semantic-release/git (si lo usás en frontend)
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 1) Instalar semantic-release + plugins en la RAÍZ (para resolverlos "hacia arriba")
      - name: Install semantic-release plugins (root)
        working-directory: .
        run: npm ci

      # 2) Instalar dependencias del frontend (si las tiene)
      - name: Install deps (frontend)
        working-directory: frontend
        run: npm ci

      # 3) Correr semantic-release desde el frontend usando plugins instalados en raíz
      - name: semantic-release (frontend)
        working-directory: frontend
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease-backend:
    name: Pre-release Backend (microservices)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - { name: gateway,      path: "backend/gateway",               tag: "gateway-v*" }
          - { name: auth-service, path: "backend/auth-service",          tag: "auth-service-v*" }
          - { name: event-service, path: "backend/event-service",        tag: "event-service-v*" }
          - { name: ticket-service, path: "backend/ticket-service",      tag: "ticket-service-v*" }
          - { name: payment-service, path: "backend/payment-service",    tag: "payment-service-v*" }
          - { name: notification-service, path: "backend/notification-service", tag: "notification-service-v*" }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Instala semantic-release y plugins en la RAÍZ (los micros Java no tienen package.json)
      - name: Install semantic-release plugins (root)
        working-directory: .
        run: npm ci

      # Detecta si cambió la carpeta del micro desde su último tag propio
      - name: Detect changes (${{ matrix.svc.name }})
        id: changed
        shell: bash
        run: |
          set -e
          LAST_TAG=$(git tag --list '${{ matrix.svc.tag }}' --sort=-v:refname | head -n1 || true)
          echo "LAST_TAG=$LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if git diff --name-only "$LAST_TAG"...HEAD | grep -q '^${{ matrix.svc.path }}/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: semantic-release (${{ matrix.svc.name }})
        if: steps.changed.outputs.changed == 'true'
        working-directory: ${{ matrix.svc.path }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-prerelease:
    name: Docker prerelease images (GHCR)
    runs-on: ubuntu-latest
    needs: [prerelease-frontend, prerelease-backend]
    strategy:
      matrix:
        svc:
          - { name: frontend, path: "frontend", image: "ticketera-frontend" }
          - { name: gateway,  path: "backend/gateway", image: "ticketera-gateway" }
          - { name: auth,     path: "backend/auth-service", image: "ticketera-auth-service" }
          - { name: event,    path: "backend/event-service", image: "ticketera-event-service" }
          - { name: ticket,   path: "backend/ticket-service", image: "ticketera-ticket-service" }
          - { name: payment,  path: "backend/payment-service", image: "ticketera-payment-service" }
          - { name: notif,    path: "backend/notification-service", image: "ticketera-notification-service" }
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: vars
        shell: bash
        run: |
          SHA=${GITHUB_SHA::7}
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          # canal 'next' para develop
          echo "tag1=${{ github.ref_name }}-next-${SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.path }}
          file: ${{ matrix.svc.path }}/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.svc.image }}:${{ steps.vars.outputs.tag1 }}
